aws:
  accessKey: test-access-key
  secretKey: test-secret-access-key
  s3:
    endpoint: http://localhost:4566
    bucketName: media-bucket
  dynamodb:
    endpoint: http://localhost:4566
  sqs:
    endpoint: http://localhost:4566
    queueName: MediaQueue.fifo
    groupId: media
    queueUrl: http://localhost:4566/000000000000/${aws.sqs.queueName}
    